name: Publish Docker image to GHCR

on:
  push:
    branches:
      - main  # Change to your default branch
    paths:
      - Dockerfile
      - '**/*.sh'
      - '.github/workflows/publish.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image name
        run: echo "IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/vps_gen_v4:latest" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}

      - name: Push Docker image to GHCR
        run: docker push ${{ env.IMAGE_NAME }}
